### ISSUE TITLE
[workaround] openssl 0.9.24 error on Arch linux

### ISSUE THREAD

**Issue by naufraghi** [rasky/r64emu#5]
```
   Compiling openssl-sys v0.9.39
   Compiling openssl v0.9.24
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/naufraghi/Documents/src/r64/target/debug/build/openssl-f877673f7fe1e6c6/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/naufraghi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

The problem is hidden in a build dependency of `sdl2-sys` 0.31.0 that depends on an old `reqwest` 0.7.x that in turn depends on an old `hyper-tls` ... till the old `openssl` v0.9.24 that does not build.

A workaround is to use some env vars, found on [aur/system76-firmware-daemon](https://aur.archlinux.org/packages/system76-firmware-daemon/): 

```
OPENSSL_LIB_DIR="/usr/lib/openssl-1.0" OPENSSL_INCLUDE_DIR="/usr/include/openssl-1.0" cargo build
```

The problem should be solved upgrading to `sdl2` 0.32.0 (once released, still in beta) that depends on a newer `reqwest` 0.9

**Comment by rasky** [comment]
Workaround for ubuntu:
```
OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl cargo build
```

**Comment by rasky** [comment]
Upgraded to a newer `rust-sdl2` that doesn't use `reqwest` anymore. Can anybody confirm this is fixed now?
